version: '3.8'

services:
  # Redis для хранения сигнатур и конфигурации
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - waf-net

  # Сервис для управления сигнатурами
  signaturedb:
    image: signaturedb
    build:
      context: ./signaturedb
    ports:
      - "8082:8082"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - waf-net

  # Анализатор запросов
  analyzer:
    image: analyzer
    build:
      context: ./analyzer
    ports:
      - "8083:8083"
    networks:
      - waf-net

  # Сам WAF Proxy
  wafproxy:
    image: wafproxy
    build:
      context: ./wafproxy
    ports:
      - "${WAF_PORT:-8081}:${WAF_PORT:-8081}" # Динамический порт из конфигурации
    environment:
      - TARGET_URL=http://192.168.200.50:7000
      - REDIS_ADDR=redis:6379
      - ANALYZER_URL=http://analyzer:8083/analyze
      - PORT=${WAF_PORT:-8081}
    depends_on:
      - redis
      - analyzer
    networks:
      - waf-net

  # Веб-интерфейс для управления WAF
  waf-admin:
    image: waf-admin
    build:
      context: ./waf-admin
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - WAFPROXY_URL=http://wafproxy:8081
    depends_on:
      - redis
      - wafproxy
    networks:
      - waf-net

networks:
  waf-net:

volumes:

  redis_data:
